version: '3.8'
services:
  # Django app
  backend_courses:
    container_name: boomslag_ms_courses
    build: .
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8004"
    volumes:
      - .:/app
    ports:
      - 8004:8004
  # Event Queue Kafka
  queue_courses:
    build: .
    command: >
      sh -c "python consumer.py"