# Generated by Django 3.2.16 on 2023-03-05 23:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_episodecompletion'),
    ]

    operations = [
        migrations.AddField(
            model_name='episodecompletion',
            name='course',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='courses.course'),
            preserve_default=False,
        ),
    ]
