# Generated by Django 3.2.16 on 2023-03-19 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_wishlist_wishlistitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='sold',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
