# Generated by Django 3.2.16 on 2023-03-22 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_alter_course_sold'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='stock',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
